---
- hosts: web
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=latest

    - name: nginx chancge config
      template:
        src: templates/8080.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
         - start nginx

    - name: Enable NGINX service 
      systemd: 
        name: nginx
        enabled: yes


      
  handlers:
    - name: start nginx
      systemd:
        name: nginx
        state: started
        enabled: True
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
