# -*- mode: ruby -*-
# vim: set ft=ruby :


MACHINES = {
  :selinux2 => {
        :box_name => "centos/8",

        #:box_version => "2004.01",
        #:provision => "test.sh",       
  },
}


Vagrant.configure("2") do |config|


  MACHINES.each do |boxname, boxconfig|


      config.vm.define boxname do |box|


        box.vm.box = boxconfig[:box_name]


        box.vm.host_name = "selinux"
        box.vm.network "forwarded_port", guest: 4881, host: 4881


        box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "1024"]
              needsController = false
        end


        box.vm.provision "shell", inline: <<-SHELL
          #install epel-release
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          dnf config-manager --set-enabled powertools
          dnf install epel-release epel-next-release
          #install nginx
          dnf install -y nginx
          #change nginx port
          sed -ie 's/:80/:4881/g' /etc/nginx/nginx.conf
          sed -i 's/listen       80 default_server;/listen       4881 default_server;/' /etc/nginx/nginx.conf
          #disable SELinux
          setenforce 0
          #start nginx
          systemctl start nginx
          systemctl status nginx
          #check nginx port
          ss -tlpn | grep 4881
          # install  policycoreutils-python-utils
          dnf install -y policycoreutils-python-utils
        SHELL
    end
  end
end

